#!/bin/sh

# Change sim card
echo 0 > /sys/class/leds/sim-sel/brightness
echo 0 > /sys/class/leds/sim-en/brightness
sleep 1
echo 1 > /sys/class/leds/sim-en/brightness
sleep 2


# Prepare the modem
AID=$(qmicli -p -d /dev/rpmsg0 --uim-get-card-status | grep -E "([A-Z0-9]{2}:){15}[A-Z0-9]{2}" | xargs)
while [ -z "$AID" ]; do
        sleep 2
        AID=$(qmicli -p -d /dev/rpmsg0 --uim-get-card-status | grep -E "([A-Z0-9]{2}:){15}[A-Z0-9]{2}" | xargs)
done

echo "AID: $AID" > /tmp/qmilog

qmicli -p -d /dev/rpmsg0 --uim-change-provisioning-session="slot=1,activate=yes,session-type=primary-gw-provisioning,aid=$AID"