#!/bin/sh /etc/rc.common

START=69 # 执行的顺序，按照字符串顺序排序并不是数字排序
STOP=69
SERVICE=app
PROG=/usr/bin/sim
USE_PROCD=1 # 使用procd启动

# start_service 函数必须要重新定义
start_service()
{
	echo service simservice start
    procd_open_instance  # 创建一个实例， 在 procd 看来一个应用程序可以多个实例
    procd_set_param command $PROG # sim执行的命令是"/usr/bin/sim" 
    procd_close_instance # 关闭实例
}

